### ISSUE TITLE
Entity question

### ISSUE THREAD

**Issue by xbmcnut** [bruxy70/Irrigation-with-display#2]
Hi there. Great project but what does your `variable.irrigation_24h` do?

**Comment by bruxy70** [comment]
It remembers if the irrigation program was triggered (manually) in the last 24 hours. In such case it will skip the schedule.

**Comment by xbmcnut** [comment]
Brilliant, thank you!

**Comment by xbmcnut** [comment]
Sorry, but could you share the yaml for that?
