### ISSUE TITLE
ID nextion_display

### ISSUE THREAD

**Issue by DirkTas67** [bruxy70/Irrigation-with-display#5]
Hello Vaclav,

Couldn't find ID 'nextion_display'. Please check you have defined an ID with that name in your configuration.
Is this id only available when the nextion display is connected to the sonoff ? it is not right now and I get this error.

Regards,

**Comment by bruxy70** [comment]
Thanks. It is corrected now.

**Comment by DirkTas67** [comment]
Thank you, does you advanced yaml also need this?
